import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const tools = [
  {
    key: '5Whys',
    namePlain: 'Ask Why Five Times',
    nameTech: '5 Whys',
    description: 'Structured root cause probing for frontline teams.',
    category: 'Problem Solving',
    difficulty: 'Easy',
    estTime: '<30m',
    pitfalls: ['Stopping at symptoms', 'Skipping validation with team'],
    nextToolKeys: ['PDSA'],
    templates: ['https://www.ihi.org/resources/Pages/Tools/FiveWhysTool.aspx'],
  },
  {
    key: 'PDSA',
    namePlain: 'Test a Change Quickly',
    nameTech: 'Plan-Do-Study-Act',
    description: 'Rapid-cycle experiment to validate a change idea.',
    category: 'Learning',
    difficulty: 'Medium',
    estTime: '1-2h',
    pitfalls: ['Planning too large a test', 'Skipping study step'],
    nextToolKeys: ['RunChart'],
    templates: ['https://www.ahrq.gov/evidencenow/tools/pdsa.html'],
  },
  {
    key: 'RunChart',
    namePlain: 'Track Measures Over Time',
    nameTech: 'Run Chart',
    description: 'Time-series view to detect signals while testing changes.',
    category: 'Measurement',
    difficulty: 'Easy',
    estTime: '1h',
    pitfalls: ['Too few data points', 'No median line'],
    nextToolKeys: ['ControlChart'],
    templates: ['https://www.health.state.mn.us/data/qi/tools/runchart.html'],
  },
  {
    key: 'ControlChart',
    namePlain: 'Variation Tracking Chart',
    nameTech: 'SPC Chart',
    description: 'Statistical process control chart for stability analysis.',
    category: 'Measurement',
    difficulty: 'Advanced',
    estTime: '2-3h',
    pitfalls: ['Misidentifying rules', 'Poor subgrouping'],
    nextToolKeys: ['Capability'],
    templates: ['https://www.ahrq.gov/chsp/tools/quality-improvement/control-charts.html'],
  },
  {
    key: 'CheckSheet',
    namePlain: 'Simple Data Tally',
    nameTech: 'Check Sheet',
    description: 'Structured form to capture counts or observations quickly.',
    category: 'Measurement',
    difficulty: 'Easy',
    estTime: '<30m',
    pitfalls: ['Unclear definitions', 'Inconsistent recording'],
    nextToolKeys: ['RunChart'],
    templates: ['https://www.gembapantarei.com/2009/05/check_sheet_template.html'],
  },
  {
    key: 'GembaObservation',
    namePlain: 'Go See the Work',
    nameTech: 'Gemba Observation',
    description: 'Direct observation of the process to capture facts before measuring.',
    category: 'Measurement',
    difficulty: 'Easy',
    estTime: '1h',
    pitfalls: ['Jumping to conclusions', 'Not involving team'],
    nextToolKeys: ['CheckSheet'],
    templates: ['https://www.goleansixsigma.com/gemba-walk/'],
  },
  {
    key: 'Histogram',
    namePlain: 'Visualize Value Spread',
    nameTech: 'Histogram',
    description: 'Frequency distribution to understand variation in a snapshot.',
    category: 'Measurement',
    difficulty: 'Medium',
    estTime: '1-2h',
    pitfalls: ['Wrong bin size', 'Forgetting context'],
    nextToolKeys: ['ControlChart'],
    templates: ['https://www.itl.nist.gov/div898/handbook/eda/section3/histogra.htm'],
  },
  {
    key: 'VSM',
    namePlain: 'Map the Whole Process',
    nameTech: 'Value Stream Map',
    description: 'Visual map of material, information, and time across the process.',
    category: 'Process',
    difficulty: 'Advanced',
    estTime: '4h',
    pitfalls: ['Too much detail', 'No team involvement'],
    nextToolKeys: ['KaizenEvent', 'StandardWork'],
    templates: ['https://www.lean.org/WhoWeAre/NewsArticleDocuments/ValueStreamMapping.pdf'],
  },
  {
    key: 'Spaghetti',
    namePlain: 'Trace the Walk Pattern',
    nameTech: 'Spaghetti Diagram',
    description: 'Layout sketch showing motion and travel waste.',
    category: 'Process',
    difficulty: 'Easy',
    estTime: '1h',
    pitfalls: ['No observation', 'Ignoring workarounds'],
    nextToolKeys: ['5S'],
    templates: ['https://www.goleansixsigma.com/spaghetti-diagram/'],
  },
  {
    key: 'WasteWalk',
    namePlain: 'Look for Waste',
    nameTech: 'Waste Walk',
    description: 'Structured observation to find Lean wastes.',
    category: 'Process',
    difficulty: 'Easy',
    estTime: '1h',
    pitfalls: ['Blame focus', 'No follow-up'],
    nextToolKeys: ['5S', 'VisualMgmt'],
    templates: ['https://www.goleansixsigma.com/waste-walk-template/'],
  },
  {
    key: '5S',
    namePlain: 'Organize the Workspace',
    nameTech: '5S',
    description: 'Sort, set in order, shine, standardize, sustain for reliability.',
    category: 'Process',
    difficulty: 'Medium',
    estTime: '2-3h',
    pitfalls: ['No sustainment', 'Too broad scope'],
    nextToolKeys: ['StandardWork'],
    templates: ['https://www.goleansixsigma.com/free-5s-training-download/'],
  },
  {
    key: 'VisualMgmt',
    namePlain: 'Make the Work Visible',
    nameTech: 'Visual Management',
    description: 'Signals, cues, boards and visuals to ensure clarity.',
    category: 'Process',
    difficulty: 'Easy',
    estTime: '<1h',
    pitfalls: ['Too cluttered', 'No ownership'],
    nextToolKeys: ['DailyHuddle'],
    templates: ['https://www.lean.org/WhoWeAre/NewsArticleDocuments/visual_management.pdf'],
  },
  {
    key: 'FMEA',
    namePlain: 'Failure Prevention Worksheet',
    nameTech: 'FMEA',
    description: 'Prioritize risk via severity, occurrence, detection scoring.',
    category: 'Safety',
    difficulty: 'Advanced',
    estTime: '3-4h',
    pitfalls: ['No scoring alignment', 'No action follow-through'],
    nextToolKeys: ['ControlPlan'],
    templates: ['https://www.ihi.org/resources/Pages/Tools/FailureModesandEffectsAnalysisTool.aspx'],
  },
  {
    key: 'ForcingFunction',
    namePlain: 'Make the Right Way the Easy Way',
    nameTech: 'Forcing Function',
    description: 'Design steps so errors cannot happen.',
    category: 'Safety',
    difficulty: 'Medium',
    estTime: '2h',
    pitfalls: ['Ignoring usability', 'Not testing with users'],
    nextToolKeys: ['StandardWork'],
    templates: ['https://psnet.ahrq.gov/primer/reducing-and-preventing-adverse-drug-events'],
  },
  {
    key: 'DailyHuddle',
    namePlain: 'Daily Huddle',
    nameTech: 'Daily Huddle',
    description: '2-5 minute stand-up to review metrics and barriers.',
    category: 'Sustainment',
    difficulty: 'Easy',
    estTime: 'Daily 5m',
    pitfalls: ['No follow-up', 'Too long'],
    nextToolKeys: ['ControlPlan'],
    templates: ['https://www.ihi.org/resources/Pages/Changes/DailyHuddles.aspx'],
  },
  {
    key: 'GoodCatch',
    namePlain: 'Capture Near Miss',
    nameTech: 'Good Catch',
    description: 'Encourage reporting and rapid learning from near misses.',
    category: 'Safety',
    difficulty: 'Easy',
    estTime: '<30m',
    pitfalls: ['No feedback loop', 'Punitive response'],
    nextToolKeys: ['5Whys'],
    templates: ['https://www.henryford.com/-/media/files/henry-ford/hcp/quality/patient-safety/aha-good-catch-toolkit.pdf'],
  },
  {
    key: 'RCA2',
    namePlain: 'Deep Dive Investigation',
    nameTech: 'RCA²',
    description: 'Comprehensive root cause analysis for sentinel events.',
    category: 'Safety',
    difficulty: 'Advanced',
    estTime: '4-6h',
    pitfalls: ['Lack of psychological safety', 'No implementation'],
    nextToolKeys: ['ControlPlan'],
    templates: ['https://www.ahrq.gov/patient-safety/resources/rca.html'],
  },
  {
    key: 'ApparentCauseAnalysis',
    namePlain: 'Rapid Cause Review',
    nameTech: 'Apparent Cause Analysis',
    description: 'Structured review for recurring events to spot contributing factors.',
    category: 'Safety',
    difficulty: 'Medium',
    estTime: '1-2h',
    pitfalls: ['No data validation', 'Not involving front line'],
    nextToolKeys: ['PDSA'],
    templates: ['https://www.childrenscolorado.org/globalassets/community/safety/aca-template.pdf'],
  },
  {
    key: 'FailureModeAnalysis',
    namePlain: 'Failure Mode Analysis',
    nameTech: 'Failure Mode Analysis',
    description: 'Look ahead to spot system vulnerabilities.',
    category: 'Safety',
    difficulty: 'Advanced',
    estTime: '3h',
    pitfalls: ['Too theoretical', 'No prioritization'],
    nextToolKeys: ['RecoveryProtocol'],
    templates: ['https://www.ismp.org/resources/failure-mode-and-effects-analysis'],
  },
  {
    key: 'RecoveryProtocol',
    namePlain: 'Recovery Playbook',
    nameTech: 'Recovery Protocol',
    description: 'Guide teams to stabilize and recover during system failure.',
    category: 'Safety',
    difficulty: 'Medium',
    estTime: '2h',
    pitfalls: ['No simulation', 'Unclear roles'],
    nextToolKeys: ['ControlPlan'],
    templates: ['https://www.jointcommission.org/resources/patient-safety-topics/sentinel-event/quick-safety-issue-45/'],
  },
  {
    key: 'DMAIC',
    namePlain: 'Structured Problem-Solving Roadmap',
    nameTech: 'DMAIC',
    description: 'Define, Measure, Analyze, Improve, Control roadmap.',
    category: 'Framework',
    difficulty: 'Advanced',
    estTime: 'Project',
    pitfalls: ['Skipping Define', 'Weak control plan'],
    nextToolKeys: ['ControlPlan'],
    templates: ['https://www.isixsigma.com/new-to-six-sigma/dmaic/'],
  },
  {
    key: 'DMADV',
    namePlain: 'Design to Requirements',
    nameTech: 'DMADV',
    description: 'Define, Measure, Analyze, Design, Verify for new processes.',
    category: 'Framework',
    difficulty: 'Advanced',
    estTime: 'Project',
    pitfalls: ['Not validating voice of customer', 'Late verification'],
    nextToolKeys: ['Capability'],
    templates: ['https://asq.org/quality-resources/dmadv'],
  },
  {
    key: 'Capability',
    namePlain: 'Process Capability Check',
    nameTech: 'Cp/Cpk',
    description: 'Quantify how well process meets specification.',
    category: 'Measurement',
    difficulty: 'Advanced',
    estTime: '2-3h',
    pitfalls: ['Wrong distribution', 'Unstable process'],
    nextToolKeys: ['ControlChart'],
    templates: ['https://www.moresteam.com/toolbox/process-capability-analysis.cfm'],
  },
  {
    key: 'DOE',
    namePlain: 'Test Multiple Changes at Once',
    nameTech: 'Design of Experiments',
    description: 'Structured multi-factor testing to optimize change.',
    category: 'Advanced Analysis',
    difficulty: 'Expert',
    estTime: 'Project',
    pitfalls: ['Too many factors', 'No replication'],
    nextToolKeys: ['Regression'],
    templates: ['https://www.itl.nist.gov/div898/handbook/pri/pri.htm'],
  },
  {
    key: 'Regression',
    namePlain: 'Find Driver Relationships',
    nameTech: 'Regression Analysis',
    description: 'Quantify relationships between factors and outcomes.',
    category: 'Advanced Analysis',
    difficulty: 'Expert',
    estTime: 'Project',
    pitfalls: ['Overfitting', 'Ignoring residuals'],
    nextToolKeys: ['ControlPlan'],
    templates: ['https://www.itl.nist.gov/div898/handbook/pmd/section1/pmd141.htm'],
  },
  {
    key: 'StandardWork',
    namePlain: 'Document the Best Way',
    nameTech: 'Standard Work',
    description: 'Agreed method for consistency and training.',
    category: 'Sustainment',
    difficulty: 'Medium',
    estTime: '1-2h',
    pitfalls: ['No visual job aids', 'Ignoring updates'],
    nextToolKeys: ['ControlPlan'],
    templates: ['https://www.goleansixsigma.com/standard-work-combination-sheet/'],
  },
  {
    key: 'Kanban',
    namePlain: 'Signal the Workload',
    nameTech: 'Kanban',
    description: 'Visual pull system to match demand and capacity.',
    category: 'Process',
    difficulty: 'Medium',
    estTime: '1-2h',
    pitfalls: ['Ignoring limits', 'Not adjusting to demand'],
    nextToolKeys: ['DailyHuddle'],
    templates: ['https://kanbanize.com/kanban-resources/getting-started/what-is-kanban'],
  },
  {
    key: 'TaktTime',
    namePlain: 'Balance Demand and Supply',
    nameTech: 'Takt Time',
    description: 'Align staffing cadence with demand for flow.',
    category: 'Process',
    difficulty: 'Medium',
    estTime: '1h',
    pitfalls: ['Wrong demand data', 'No cross training'],
    nextToolKeys: ['StandardWork'],
    templates: ['https://www.lean.org/WhoWeAre/NewsArticleDocuments/TaktTime.pdf'],
  },
  {
    key: 'KaizenEvent',
    namePlain: 'Rapid Improvement Workshop',
    nameTech: 'Kaizen Event',
    description: 'Focused multi-day event to redesign a process segment.',
    category: 'Process',
    difficulty: 'Advanced',
    estTime: '3-5d',
    pitfalls: ['No preparation', 'No sustainment plan'],
    nextToolKeys: ['StandardWork', 'ControlPlan'],
    templates: ['https://www.lean.org/WhoWeAre/NewsArticleDocuments/kaizen_event.pdf'],
  },
  {
    key: 'A3',
    namePlain: 'Tell the Improvement Story',
    nameTech: 'A3 Report',
    description: 'Concise 9-box storytelling template connecting problem, root cause, countermeasures, and sustainment.',
    category: 'Sustainment',
    difficulty: 'Medium',
    estTime: '1-2h',
    pitfalls: ['Filling in hindsight', 'Skipping experimentation'],
    nextToolKeys: ['ControlPlan'],
    templates: ['https://www.lean.org/WhoWeAre/NewsArticleDocuments/A3_Thinking.pdf'],
  },
];

const packages = [
  {
    key: 'QuickWin',
    name: 'Quick Win Package',
    toolKeys: ['5Whys', 'PDSA', 'VisualMgmt'],
    description: 'Use when you need a fast fix with limited data.',
    whenBest: 'Frontline problem solving with contained scope.',
    pitfalls: ['Skipping validation', 'Not engaging team'],
    nextPackageKeys: ['Efficiency'],
  },
  {
    key: 'DataDriven',
    name: 'Data-Driven Package',
    toolKeys: ['CheckSheet', 'RunChart', 'ControlChart'],
    description: 'Build measurement discipline to understand variation.',
    whenBest: 'When the question is “Is the change making a difference?”',
    pitfalls: ['No operational definitions', 'Too few data points'],
    nextPackageKeys: ['QuickWin'],
  },
  {
    key: 'ProcessRedesign',
    name: 'Process Redesign Package',
    toolKeys: ['VSM', 'KaizenEvent', 'StandardWork'],
    description: 'Ideal for end-to-end flow redesign and waste removal.',
    whenBest: 'Cross-functional teams redesigning process flow.',
    pitfalls: ['No follow-through', 'Lack of leadership support'],
    nextPackageKeys: ['Efficiency'],
  },
  {
    key: 'Safety',
    name: 'Safety Assurance Package',
    toolKeys: ['FMEA', 'ForcingFunction', 'DailyHuddle'],
    description: 'Prevent harm and build reliable recovery.',
    whenBest: 'High-risk processes or incident response.',
    pitfalls: ['No patient voice', 'Not prioritizing high RPN'],
    nextPackageKeys: ['DataDriven'],
  },
  {
    key: 'Efficiency',
    name: 'Efficiency Boost Package',
    toolKeys: ['WasteWalk', '5S', 'VisualMgmt'],
    description: 'Remove waste and simplify work routines.',
    whenBest: 'Throughput, wait time, or motion waste concerns.',
    pitfalls: ['No sustainment', 'Scope creep'],
    nextPackageKeys: ['ProcessRedesign'],
  },
];

const decisionNodes = [
  {
    key: 'entry.goal',
    question: "What's your primary goal?",
    options: [
      { label: 'Fix an immediate problem', value: 'A', next: 'A.scope' },
      { label: 'Improve an existing process', value: 'B', next: 'B.aspect' },
      { label: 'Measure/track performance', value: 'C', next: 'C.measure' },
      { label: 'Prevent future problems', value: 'D', next: 'D.prevent' },
      { label: 'Respond to incident/event', value: 'E', next: 'E.type' },
    ],
    nextNodeKeys: ['A.scope', 'B.aspect', 'C.measure', 'D.prevent', 'E.type'],
    pathTag: null,
  },
  {
    key: 'A.scope',
    question: 'How focused is the issue?',
    options: [
      { label: 'One team or room', value: 'contained', recommend: { package: 'QuickWin' }, pathTag: 'ProblemSolving' },
      { label: 'Spans multiple units', value: 'broad', recommend: { framework: 'DMAIC' }, pathTag: 'ProblemSolving' },
    ],
    nextNodeKeys: [],
    pathTag: 'ProblemSolving',
  },
  {
    key: 'B.aspect',
    question: 'Which aspect needs improvement?',
    options: [
      { label: 'Flow/time', value: 'flow', next: 'B.flow' },
      { label: 'Quality/defects', value: 'quality', next: 'B.quality' },
      { label: 'Roles/clarity', value: 'roles', recommend: { tools: ['StandardWork', 'DailyHuddle'] }, pathTag: 'ProcessImprovement' },
    ],
    nextNodeKeys: ['B.flow', 'B.quality'],
    pathTag: 'ProcessImprovement',
  },
  {
    key: 'B.flow',
    question: 'Where are the delays?',
    options: [
      { label: 'Unknown', value: 'unknown', recommend: { tools: ['VSM', 'Spaghetti', 'TaktTime'] }, pathTag: 'ProcessImprovement' },
      { label: 'Known bottleneck', value: 'known', recommend: { tools: ['WasteWalk', '5S'] }, pathTag: 'ProcessImprovement' },
    ],
    nextNodeKeys: [],
    pathTag: 'ProcessImprovement',
  },
  {
    key: 'B.quality',
    question: 'Defect type?',
    options: [
      { label: 'Human error', value: 'human', recommend: { tools: ['5Whys', 'VisualMgmt'] }, pathTag: 'ProcessImprovement' },
      { label: 'Process reliability', value: 'process', recommend: { package: 'Safety' }, pathTag: 'ProcessImprovement' },
    ],
    nextNodeKeys: [],
    pathTag: 'ProcessImprovement',
  },
  {
    key: 'C.measure',
    question: 'What do you need to measure?',
    options: [
      { label: 'Baseline performance', value: 'baseline', recommend: { tools: ['CheckSheet', 'RunChart'] }, pathTag: 'Measurement' },
      { label: 'Monitor a test of change', value: 'test', recommend: { tools: ['RunChart', 'PDSA'] }, pathTag: 'Measurement' },
      { label: 'Control ongoing performance', value: 'control', recommend: { tools: ['ControlChart', 'Capability'] }, pathTag: 'Measurement' },
    ],
    nextNodeKeys: [],
    pathTag: 'Measurement',
  },
  {
    key: 'D.prevent',
    question: 'Where to focus prevention?',
    options: [
      { label: 'Known failure modes', value: 'known', recommend: { tools: ['FMEA', 'ForcingFunction'] }, pathTag: 'Prevention' },
      { label: 'Need early warning', value: 'warning', recommend: { tools: ['VisualMgmt', 'DailyHuddle'] }, pathTag: 'Prevention' },
    ],
    nextNodeKeys: [],
    pathTag: 'Prevention',
  },
  {
    key: 'E.type',
    question: 'What type of incident?',
    options: [
      { label: 'Sentinel Event', value: 'sentinel', recommend: { package: 'Safety', extras: ['RCA2'] }, pathTag: 'Incident:Sentinel' },
      { label: 'Near Miss', value: 'nearmiss', recommend: { tools: ['GoodCatch', '5Whys'] }, pathTag: 'Incident:NearMiss' },
      { label: 'Recurring Issue', value: 'recurring', recommend: { tools: ['ApparentCauseAnalysis', 'PDSA'] }, pathTag: 'Incident:Recurring' },
      { label: 'System Failure', value: 'system', recommend: { tools: ['FailureModeAnalysis', 'RecoveryProtocol'] }, pathTag: 'Incident:SystemFailure' },
    ],
    nextNodeKeys: [],
    pathTag: 'Incident',
  },
];

const rationales = [
  {
    toolKey: 'PDSA',
    pathTag: 'PDSA@ProblemSolving',
    textPlain: 'Use quick PDSA cycles to prove the fix works before rolling out.',
    textTech: 'Run rapid-cycle experiments to validate the containment strategy before standardizing.',
  },
  {
    toolKey: 'PDSA',
    pathTag: 'PDSA@ProcessImprovement',
    textPlain: 'Test redesigned steps with staff to confirm flow improves.',
    textTech: 'Leverage iterative PDSA to validate future-state map hypotheses and quantify flow gains.',
  },
  {
    toolKey: 'RunChart',
    pathTag: 'RunChart@Measurement',
    textPlain: 'Track baseline data to show the story before changes.',
    textTech: 'Use time-series plotting to reveal baseline variation and shifts over time.',
  },
  {
    toolKey: 'RunChart',
    pathTag: 'RunChart@PDSA',
    textPlain: 'Monitor each PDSA cycle to see if the change is helping.',
    textTech: 'Detect non-random signals linked to the tested change using run chart rules.',
  },
  {
    toolKey: 'ControlChart',
    pathTag: 'ControlChart@Measurement',
    textPlain: 'Stabilize performance with control limits and rules.',
    textTech: 'Apply SPC to distinguish common vs special cause signals for sustained control.',
  },
  {
    toolKey: 'FMEA',
    pathTag: 'FMEA@Incident:Sentinel',
    textPlain: 'Score each failure mode to prevent recurrence.',
    textTech: 'Prioritize high RPN risks and define mitigation actions after sentinel review.',
  },
  {
    toolKey: '5Whys',
    pathTag: '5Whys@Incident:NearMiss',
    textPlain: 'Ask why five times with the team to catch the weak link.',
    textTech: 'Rapid causal probing to surface contributing factors from the near miss.',
  },
  {
    toolKey: 'CheckSheet',
    pathTag: 'CheckSheet@Measurement',
    textPlain: 'Quickly tally observations without fancy systems.',
    textTech: 'Structured manual data capture ensures consistent operational definitions.',
  },
  {
    toolKey: 'VSM',
    pathTag: 'VSM@ProcessImprovement',
    textPlain: 'See where patients and staff wait and why.',
    textTech: 'Value stream mapping surfaces bottlenecks and redesign opportunities across the flow.',
  },
  {
    toolKey: 'GoodCatch',
    pathTag: 'GoodCatch@Incident:NearMiss',
    textPlain: 'Celebrate the catch and spread the learning quickly.',
    textTech: 'Formalize near-miss capture to feed your safety learning system.',
  },
];

async function main() {
  await prisma.rationale.deleteMany();
  await prisma.decisionNode.deleteMany();
  await prisma.toolPackage.deleteMany();
  await prisma.tool.deleteMany();

  for (const tool of tools) {
    await prisma.tool.create({ data: tool });
  }

  for (const pkg of packages) {
    await prisma.toolPackage.create({ data: pkg });
  }

  for (const node of decisionNodes) {
    await prisma.decisionNode.create({ data: node });
  }

  for (const rationale of rationales) {
    await prisma.rationale.create({ data: rationale });
  }
}

main()
  .catch((e) => {
    // eslint-disable-next-line no-console
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
